name: Solar Theme
url: /solar-theme-jekyll
description: A stylish blog using the Solarized color palette

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: rouge

gems: [jekyll-paginate, github-pages, jekyll-feed, jemoji]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
